# Generated by Django 5.0.3 on 2024-04-14 18:09

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_ordem_data_ordem_alter_ordem_diagnostico_and_more'), # Migração anterior
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Adiciona o campo 'autor' ao modelo 'Cliente'
        migrations.AddField(
            model_name='cliente',
            name='autor',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Autor da cliente'), # Adiciona um verbose_name descritivo
            preserve_default=False, # Atribui um valor padrão explicitamente
        ),
    ]
