# Generated by Django 4.2.11 on 2024-03-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_clientes_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
