# Generated by Django 5.0.3 on 2024-04-14 18:20

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_cliente_autor'), # Migração anterior
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Adiciona o campo 'autor' ao modelo 'Ordem'
        migrations.AddField(
            model_name='ordem',
            name='autor',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Autor da ordem'), # Adiciona um verbose_name descritivo
            preserve_default=False, # Atribui um valor padrão explicitamente
        ),
        # Adiciona o campo 'autor' ao modelo 'Veiculo'
        migrations.AddField(
            model_name='veiculo',
            name='autor',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Autor do veículo'), # Adiciona um verbose_name descritivo
            preserve_default=False, # Atribui um valor padrão explicitamente
        ),
    ]
