# Generated by Django 4.2.11 on 2024-03-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_rename_clientes_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=250)),
                ('motor', models.CharField(max_length=150)),
                ('ano', models.CharField(max_length=50)),
            ],
        ),
    ]
