# Generated by Django 5.0.3 on 2024-04-16 23:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_rename_data_ordem_ordem_data_criacao'),
    ]

    operations = [
        # Adiciona um novo campo chamado 'observacoes' ao modelo 'Ordem'
        migrations.AddField(
            model_name='ordem',
            name='observacoes',
            field=models.CharField(
                max_length=250,
                blank=True,  # O campo pode ser deixado em branco
                # Adicione um valor padrão se apropriado
                # default='Insira as observações aqui',
                # Adicione um comentário para explicar o propósito do campo
                help_text='Observações adicionais para a ordem.'
            ),
        ),
    ]
