# Generated by Django 4.2.11 on 2024-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_veiculo_delete_veiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='vazio', max_length=50),
        ),
    ]
