# Generated by Django 5.0.3 on 2024-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_ordem_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecasservico',
            old_name='ordem_id',
            new_name='ordem',
        ),
        migrations.RenameField(
            model_name='pecasservico',
            old_name='peca_id',
            new_name='peca',
        ),
        migrations.AddField(
            model_name='ordem',
            name='status_ordem',
            field=models.CharField(choices=[('A', 'Em Execução - aprovado pelo cliente'), ('B', 'Em Aberto - aguardando aprovação pelo cliente'), ('C', 'Em Aberto - aguardando peças'), ('D', 'Finalizado'), ('E', 'Finalizado - interrompido pelo cliente')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='cadastropecas',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='condicao',
            field=models.CharField(choices=[('A', 'Normal - Proprietário veio rodando'), ('B', 'Sem funcionar - veio no guincho'), ('C', 'Com anomalia - Proprietário veio rodando'), ('D', 'Com anomalia - Veio rodando por terceiro')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='observacoes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Agendada', 'Agendada')], default='Em andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
