# Generated by Django 4.2.11 on 2024-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_veiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
