# Generated by Django 4.2.11 on 2024-03-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_veiculo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('subgrupo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('data_ordem', models.DateField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.cliente')),
                ('veiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PecasServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.ordem')),
                ('peca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.cadastropecas')),
            ],
        ),
    ]
