# Generated by Django 4.2.11 on 2024-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_cadastropecas_ordem_pecasservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropecas',
            name='nome',
            field=models.CharField(default='sem nome', max_length=150),
        ),
    ]
