# Generated by Django 4.2.11 on 2024-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_cadastropecas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='diagnostico',
            field=models.CharField(default='Descreva o problema observado', max_length=150),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
    ]
