# Generated by Django 4.2.11 on 2024-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_ordem_diagnostico_alter_ordem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='condicao',
            field=models.CharField(choices=[('A', 'Normal - Proprietário veio rodando'), ('B', 'Sem funcionar - veio no guincho'), ('C', 'Com anomalia - Proprietário veio rodando'), ('D', 'Com anomalia - Veio rodando por terceiro')], default='Normal - Proprietário veio rodando', max_length=100),
        ),
        migrations.AddField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('A', 'Em Execução - aprovado pelo cliente'), ('B', 'Em Aberto -  aguardando aprovação pelo cliente'), ('C', 'Em Aberto -  aguardando peças'), ('D', 'Finallizado'), ('E', 'Finallizado - interrompido pelo cliente')], default='Em Execução - aprovado pelo cliente', max_length=100),
        ),
    ]
